In [1]:
import pandas as pd

df = pd.read_csv("5e5eb7bd-b059-45ea-b165-7b2faf386a61_Data.csv")
df.head()

,Country Name,Country Code,Series Name,Series Code,1960 [YR1960],1961 [YR1961],1962 [YR1962],1963 [YR1963],1964 [YR1964],1965 [YR1965],...,2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
0,Afghanistan,AFG,"Prevalence of stunting, height for age (% of c...",SH.STA.STNT.ZS,..,..,..,..,..,..,...,..,..,38.2,..,..,..,44.6,..,..,..
1,Afghanistan,AFG,"Literacy rate, adult female (% of females ages...",SE.ADT.LITR.FE.ZS,..,..,..,..,..,..,...,..,..,..,..,21.6826901223905,22.6000003814697,26.6000003814697,..,..,..
2,Afghanistan,AFG,Pregnant women receiving prenatal care (%),SH.STA.ANVC.ZS,..,..,..,..,..,..,...,..,70.2,65.2,..,..,..,..,..,..,..
3,Albania,ALB,"Prevalence of stunting, height for age (% of c...",SH.STA.STNT.ZS,..,..,..,..,..,..,...,..,11.3,..,..,..,..,..,..,..,..
4,Albania,ALB,"Literacy rate, adult female (% of females ages...",SE.ADT.LITR.FE.ZS,..,..,..,..,..,..,...,..,99.0500030517578,..,..,..,..,..,97.2200012207031,..,..

In [2]:
df = df.drop(columns=["Country Code", "Series Code"])
df.head()

,Country Name,Series Name,1960 [YR1960],1961 [YR1961],1962 [YR1962],1963 [YR1963],1964 [YR1964],1965 [YR1965],1966 [YR1966],1967 [YR1967],...,2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
0,Afghanistan,"Prevalence of stunting, height for age (% of c...",..,..,..,..,..,..,..,..,...,..,..,38.2,..,..,..,44.6,..,..,..
1,Afghanistan,"Literacy rate, adult female (% of females ages...",..,..,..,..,..,..,..,..,...,..,..,..,..,21.6826901223905,22.6000003814697,26.6000003814697,..,..,..
2,Afghanistan,Pregnant women receiving prenatal care (%),..,..,..,..,..,..,..,..,...,..,70.2,65.2,..,..,..,..,..,..,..
3,Albania,"Prevalence of stunting, height for age (% of c...",..,..,..,..,..,..,..,..,...,..,11.3,..,..,..,..,..,..,..,..
4,Albania,"Literacy rate, adult female (% of females ages...",..,..,..,..,..,..,..,..,...,..,99.0500030517578,..,..,..,..,..,97.2200012207031,..,..

In [3]:
years = [str(year) for year in range(2000, 2024)]

df = df[["Country Name", "Series Name"] + 
        [col for col in df.columns if any(year in col for year in years)]]

df.head()

,Country Name,Series Name,2000 [YR2000],2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],2007 [YR2007],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Afghanistan,"Prevalence of stunting, height for age (% of c...",..,..,..,..,59.3,..,..,..,...,..,..,..,..,38.2,..,..,..,44.6,..
1,Afghanistan,"Literacy rate, adult female (% of females ages...",..,..,..,..,..,..,..,..,...,..,17.0900001525879,..,..,..,..,21.6826901223905,22.6000003814697,26.6000003814697,..
2,Afghanistan,Pregnant women receiving prenatal care (%),36.9,..,..,16.1,..,..,30.3,..,...,63.2,58.6,..,70.2,65.2,..,..,..,..,..
3,Albania,"Prevalence of stunting, height for age (% of c...",..,..,..,..,..,26.7,..,..,...,..,..,..,11.3,..,..,..,..,..,..
4,Albania,"Literacy rate, adult female (% of females ages...",..,98.25,..,..,..,..,..,..,...,..,..,..,99.0500030517578,..,..,..,..,..,97.2200012207031

In [4]:
df_long = df.melt(
    id_vars=["Country Name", "Series Name"],
    var_name="Year",
    value_name="Value"
)

df_long.head()

,Country Name,Series Name,Year,Value
0,Afghanistan,"Prevalence of stunting, height for age (% of c...",2000 [YR2000],..
1,Afghanistan,"Literacy rate, adult female (% of females ages...",2000 [YR2000],..
2,Afghanistan,Pregnant women receiving prenatal care (%),2000 [YR2000],36.9
3,Albania,"Prevalence of stunting, height for age (% of c...",2000 [YR2000],..
4,Albania,"Literacy rate, adult female (% of females ages...",2000 [YR2000],..

In [5]:
df_long["Year"] = df_long["Year"].str.extract('(\d+)')
df_long["Year"] = df_long["Year"].astype(int)

In [7]:
# Replace '..' with NaN
df_long["Value"] = df_long["Value"].replace("..", pd.NA)

# Convert to numeric
df_long["Value"] = pd.to_numeric(df_long["Value"], errors="coerce")

In [8]:
df_final = df_long.pivot_table(
    index=["Country Name", "Year"],
    columns="Series Name",
    values="Value"
).reset_index()

df_final.head()

Series Name,Country Name,Year,"Literacy rate, adult female (% of females ages 15 and above)",Pregnant women receiving prenatal care (%),"Prevalence of stunting, height for age (% of children under 5)"
0,Afghanistan,2000,NaN,36.9,NaN
1,Afghanistan,2003,NaN,16.1,NaN
2,Afghanistan,2004,NaN,NaN,59.3
3,Afghanistan,2006,NaN,30.3,NaN
4,Afghanistan,2008,NaN,36.0,NaN

In [9]:
df_final.isna().sum()

Series Name
Country Name                                                         0
Year                                                                 0
Literacy rate, adult female (% of females ages 15 and above)       840
Pregnant women receiving prenatal care (%)                        1822
Prevalence of stunting, height for age (% of children under 5)    1813
dtype: int64

In [20]:
df_model = df_final.copy()

# Drop only rows where target (stunting) is missing
df_model = df_model.dropna(subset=[
    "Prevalence of stunting, height for age (% of children under 5)"
])

# Fill missing literacy with mean
df_model["Literacy rate, adult female (% of females ages 15 and above)"] = \
df_model["Literacy rate, adult female (% of females ages 15 and above)"].fillna(
    df_model["Literacy rate, adult female (% of females ages 15 and above)"].mean()
)

# Fill missing prenatal care with mean
df_model["Pregnant women receiving prenatal care (%)"] = \
df_model["Pregnant women receiving prenatal care (%)"].fillna(
    df_model["Pregnant women receiving prenatal care (%)"].mean()
)

df_model.shape

(845, 5)

In [12]:
df_model = df_model.copy()

df_model.loc[:, "Region_Type"] = np.random.choice(
    ["Rural", "Urban"],
    size=len(df_model),
    p=[0.6, 0.4]
)

In [13]:
mask = np.random.rand(len(df_model)) < 0.1
df_model.loc[mask, "Region_Type"] = np.nan

df_model["Region_Type"].isna().sum()

np.int64(26)

In [14]:
mode_value = df_model["Region_Type"].mode()[0]
df_model["Region_Type"].fillna(mode_value, inplace=True)

df_model["Region_Type"].isna().sum()

C:\Users\Zeba Shine\AppData\Local\Temp\ipykernel_40184\2611486498.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_model["Region_Type"].fillna(mode_value, inplace=True)

np.int64(0)

In [22]:
df_model.columns

Index(['Country Name', 'Year',
       'Literacy rate, adult female (% of females ages 15 and above)',
       'Pregnant women receiving prenatal care (%)',
       'Prevalence of stunting, height for age (% of children under 5)'],
      dtype='object', name='Series Name')

In [23]:
import numpy as np

# Create Region_Type
df_model["Region_Type"] = np.random.choice(
    ["Rural", "Urban"],
    size=len(df_model),
    p=[0.6, 0.4]
)

df_model.head()

Series Name,Country Name,Year,"Literacy rate, adult female (% of females ages 15 and above)",Pregnant women receiving prenatal care (%),"Prevalence of stunting, height for age (% of children under 5)",Region_Type
2,Afghanistan,2004,73.372808,85.757125,59.3,Rural
8,Afghanistan,2013,73.372808,85.757125,40.4,Urban
12,Afghanistan,2018,73.372808,65.200000,38.2,Rural
15,Afghanistan,2022,26.600000,85.757125,44.6,Urban
67,Albania,2005,73.372808,97.100000,26.7,Urban

In [25]:
mask = np.random.rand(len(df_model)) < 0.1
df_model.loc[mask, "Region_Type"] = np.nan

In [26]:
mode_value = df_model["Region_Type"].mode()[0]
df_model["Region_Type"] = df_model["Region_Type"].fillna(mode_value)

In [27]:
df_model["Region_Type"] = df_model["Region_Type"].map({
    "Rural": 0,
    "Urban": 1
})

In [28]:
df_model.head()

Series Name,Country Name,Year,"Literacy rate, adult female (% of females ages 15 and above)",Pregnant women receiving prenatal care (%),"Prevalence of stunting, height for age (% of children under 5)",Region_Type
2,Afghanistan,2004,73.372808,85.757125,59.3,0
8,Afghanistan,2013,73.372808,85.757125,40.4,1
12,Afghanistan,2018,73.372808,65.200000,38.2,0
15,Afghanistan,2022,26.600000,85.757125,44.6,1
67,Albania,2005,73.372808,97.100000,26.7,1

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 803 entries, 0 to 802
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   800 non-null    object
 1   Series Name    798 non-null    object
 2   2000 [YR2000]  798 non-null    object
 3   2001 [YR2001]  798 non-null    object
 4   2002 [YR2002]  798 non-null    object
 5   2003 [YR2003]  798 non-null    object
 6   2004 [YR2004]  798 non-null    object
 7   2005 [YR2005]  798 non-null    object
 8   2006 [YR2006]  798 non-null    object
 9   2007 [YR2007]  798 non-null    object
 10  2008 [YR2008]  798 non-null    object
 11  2009 [YR2009]  798 non-null    object
 12  2010 [YR2010]  798 non-null    object
 13  2011 [YR2011]  798 non-null    object
 14  2012 [YR2012]  798 non-null    object
 15  2013 [YR2013]  798 non-null    object
 16  2014 [YR2014]  798 non-null    object
 17  2015 [YR2015]  798 non-null    object
 18  2016 [YR2016]  798 non-null    object
 19  2017 [YR2017]  798 non-null    object
 20  2018 [YR2018]  798 non-null    object
 21  2019 [YR2019]  798 non-null    object
 22  2020 [YR2020]  798 non-null    object
 23  2021 [YR2021]  798 non-null    object
 24  2022 [YR2022]  798 non-null    object
 25  2023 [YR2023]  798 non-null    object
dtypes: object(26)
memory usage: 163.2+ KB

In [30]:
df_model.shape

(845, 6)

In [31]:
df_model.to_csv("cleaned_child_malnutrition_data.csv", index=False)

In [32]:
df_model.to_excel("cleaned_child_malnutrition_data.xlsx", index=False)